[package]
name = "VoiceModifier2"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13"
dasp = { version = "0.11.0", features = ["signal"] }
env_logger = "0.11.5"
log = "0.4.22"
portaudio = "0.7.0"
rustfft = "6.2.0"
